#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-JavaScript-Minifier-XS
Version  : 0.11
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/G/GT/GTERMARS/JavaScript-Minifier-XS-0.11.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/G/GT/GTERMARS/JavaScript-Minifier-XS-0.11.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libj/libjavascript-minifier-xs-perl/libjavascript-minifier-xs-perl_0.11-1.debian.tar.xz
Summary  : 'XS based JavaScript minifier'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-JavaScript-Minifier-XS-lib
Requires: perl-JavaScript-Minifier-XS-man

%description
JavaScript::Minifier::XS minifies JavaScript documents by removing un-necessary whitespace

%package lib
Summary: lib components for the perl-JavaScript-Minifier-XS package.
Group: Libraries

%description lib
lib components for the perl-JavaScript-Minifier-XS package.


%package man
Summary: man components for the perl-JavaScript-Minifier-XS package.
Group: Default

%description man
man components for the perl-JavaScript-Minifier-XS package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n JavaScript-Minifier-XS-0.11
mkdir -p %{_topdir}/BUILD/JavaScript-Minifier-XS-0.11/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/JavaScript-Minifier-XS-0.11/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/JavaScript/Minifier/XS.pm

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/JavaScript/Minifier/XS/XS.so

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/JavaScript::Minifier::XS.3
